version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html/
  - source: /scripts/
    destination: /var/www/html/scripts/

permissions:
  - object: /var/www/html/
    owner: apache
    group: apache
    mode: 755
    type:
      - directory
      - file
  - object: /var/www/html/scripts/
    owner: root
    group: root
    mode: 755
    pattern: "**"
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/post_deploy.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
