version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/scripts/stop_server
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/scripts/install_dependencies
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/scripts/post_deploy.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/scripts/start_server
      timeout: 300
      runas: root
